# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'HemoLeo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HemoLeo
  pod 'SkyFloatingLabelTextField', '~> 1.0'
  pod 'FSCalendar'

end

target 'iPhone' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iPhone
  pod 'SkyFloatingLabelTextField', '~> 1.0'
  pod 'FSCalendar'

end
